name: Deploy TypeDoc on GitHub pages

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_VERSION: 16.x
  ENTRY_FILE: 'src/index.ts'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install
      - name: Create the JSON
        run: npm run generate-json
